version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 2020:80
    depends_on:
      - app-php
    container_name: nginx

  app-php:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mariadb
    container_name: app-php

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - ./tmp/database:/var/lib/mysql
    environment:
        MYSQL_DATABASE: api-app
        MARIADB_ROOT_PASSWORD: root
    ports:
      - 33060:3306
    container_name: mariadb
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge
